// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibraryRoot() {
  return window['go']['main']['App']['AddLibraryRoot']();
}

export function ApplySourceMerge(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplySourceMerge'](arg1, arg2, arg3);
}

export function ApplySourceTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplySourceTags'](arg1, arg2, arg3);
}

export function CancelAutoTag() {
  return window['go']['main']['App']['CancelAutoTag']();
}

export function Count() {
  return window['go']['main']['App']['Count']();
}

export function CountMissing() {
  return window['go']['main']['App']['CountMissing']();
}

export function DeleteManga(arg1) {
  return window['go']['main']['App']['DeleteManga'](arg1);
}

export function GetAuthor(arg1) {
  return window['go']['main']['App']['GetAuthor'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetManga(arg1) {
  return window['go']['main']['App']['GetManga'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSourceFacets() {
  return window['go']['main']['App']['GetSourceFacets']();
}

export function GetSources() {
  return window['go']['main']['App']['GetSources']();
}

export function GetUnimported() {
  return window['go']['main']['App']['GetUnimported']();
}

export function ImportAll() {
  return window['go']['main']['App']['ImportAll']();
}

export function Ingest(arg1, arg2) {
  return window['go']['main']['App']['Ingest'](arg1, arg2);
}

export function MatchSource(arg1) {
  return window['go']['main']['App']['MatchSource'](arg1);
}

export function RemoveLibraryRoot(arg1) {
  return window['go']['main']['App']['RemoveLibraryRoot'](arg1);
}

export function RemoveMissing() {
  return window['go']['main']['App']['RemoveMissing']();
}

export function Rescan() {
  return window['go']['main']['App']['Rescan']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetActiveSource(arg1) {
  return window['go']['main']['App']['SetActiveSource'](arg1);
}

export function SetDisplayTitle(arg1, arg2) {
  return window['go']['main']['App']['SetDisplayTitle'](arg1, arg2);
}

export function SetNhentaiKey(arg1) {
  return window['go']['main']['App']['SetNhentaiKey'](arg1);
}

export function SetSourceConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetSourceConfig'](arg1, arg2, arg3, arg4);
}

export function StartAutoTag(arg1) {
  return window['go']['main']['App']['StartAutoTag'](arg1);
}

export function StashGet(arg1) {
  return window['go']['main']['App']['StashGet'](arg1);
}

export function StashList() {
  return window['go']['main']['App']['StashList']();
}

export function StashRemove(arg1) {
  return window['go']['main']['App']['StashRemove'](arg1);
}

export function StashSave(arg1) {
  return window['go']['main']['App']['StashSave'](arg1);
}

export function StashSetPage(arg1, arg2) {
  return window['go']['main']['App']['StashSetPage'](arg1, arg2);
}

export function SuggestAuthors(arg1) {
  return window['go']['main']['App']['SuggestAuthors'](arg1);
}

export function SuggestTags(arg1) {
  return window['go']['main']['App']['SuggestTags'](arg1);
}

export function SuggestTagsTyped(arg1) {
  return window['go']['main']['App']['SuggestTagsTyped'](arg1);
}

export function UpdateTags(arg1, arg2) {
  return window['go']['main']['App']['UpdateTags'](arg1, arg2);
}
