// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibraryRoot() {
  return window['go']['main']['App']['AddLibraryRoot']();
}

export function Count() {
  return window['go']['main']['App']['Count']();
}

export function GetAuthor(arg1) {
  return window['go']['main']['App']['GetAuthor'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetManga(arg1) {
  return window['go']['main']['App']['GetManga'](arg1);
}

export function GetUnimported() {
  return window['go']['main']['App']['GetUnimported']();
}

export function ImportAll() {
  return window['go']['main']['App']['ImportAll']();
}

export function Ingest(arg1, arg2) {
  return window['go']['main']['App']['Ingest'](arg1, arg2);
}

export function RemoveLibraryRoot(arg1) {
  return window['go']['main']['App']['RemoveLibraryRoot'](arg1);
}

export function Rescan() {
  return window['go']['main']['App']['Rescan']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SuggestAuthors(arg1) {
  return window['go']['main']['App']['SuggestAuthors'](arg1);
}

export function SuggestTags(arg1) {
  return window['go']['main']['App']['SuggestTags'](arg1);
}

export function UpdateTags(arg1, arg2) {
  return window['go']['main']['App']['UpdateTags'](arg1, arg2);
}
