// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tag} from '../models';
import {search} from '../models';
import {config} from '../models';
import {main} from '../models';
import {scanner} from '../models';
import {stash} from '../models';

export function AddLibraryRoot():Promise<string>;

export function ApplyNhentaiMerge(arg1:number,arg2:Array<number>):Promise<Array<tag.Typed>>;

export function ApplyNhentaiTags(arg1:number,arg2:number):Promise<Array<tag.Typed>>;

export function CancelAutoTag():Promise<void>;

export function Count():Promise<number>;

export function CountMissing():Promise<number>;

export function DeleteManga(arg1:number):Promise<void>;

export function GetAuthor(arg1:number):Promise<search.Author>;

export function GetConfig():Promise<config.Config>;

export function GetManga(arg1:number):Promise<main.MangaDetail>;

export function GetSettings():Promise<main.Settings>;

export function GetUnimported():Promise<Array<main.UnimportedPreview>>;

export function ImportAll():Promise<void>;

export function Ingest(arg1:scanner.DetectedFolder,arg2:Array<string>):Promise<void>;

export function MatchNhentai(arg1:number):Promise<main.MatchResult>;

export function RemoveLibraryRoot(arg1:string):Promise<void>;

export function RemoveMissing():Promise<number>;

export function Rescan():Promise<void>;

export function Search(arg1:main.SearchArgs):Promise<Array<search.Manga>>;

export function SetNhentaiKey(arg1:string):Promise<void>;

export function StartAutoTag(arg1:main.AutoTagOptions):Promise<void>;

export function StashGet(arg1:number):Promise<stash.Entry>;

export function StashList():Promise<Array<stash.Entry>>;

export function StashRemove(arg1:number):Promise<void>;

export function StashSave(arg1:main.StashInput):Promise<number>;

export function StashSetPage(arg1:number,arg2:number):Promise<void>;

export function SuggestAuthors(arg1:string):Promise<Array<search.Author>>;

export function SuggestTags(arg1:string):Promise<Array<string>>;

export function UpdateTags(arg1:number,arg2:Array<string>):Promise<Array<tag.Typed>>;
